In [2]:
# numpy -> Array Operations   np
# pandas -> structured data analysis   pd
# matplotlib -> data visualization   plt
# seaborn -> advanced data visualization   sns
# scikit-learn -> machine learning
# keras -> deep learning
# nltk -> natural language processing

In [3]:
import numpy as np

### Create an array

In [5]:
x = np.array([6,7,5,3,1,8,9,0,2])

In [6]:
print(x)

[6 7 5 3 1 8 9 0 2]


In [7]:
y = [6,7,5,3,1,8,9,0,2]
print(y)

[6, 7, 5, 3, 1, 8, 9, 0, 2]


In [8]:
x

array([6, 7, 5, 3, 1, 8, 9, 0, 2])

In [9]:
type(x)

numpy.ndarray

In [10]:
x.dtype

dtype('int64')

In [11]:
x.size

9

In [12]:
x.shape

(9,)

In [13]:
x = np.array([6,7,5,3,1,8,9,0,2], dtype = np.int32)

In [14]:
x.dtype

dtype('int32')

In [15]:
x = np.array([6,7,5,3,1,8,9,0,2], dtype = np.float32)

In [16]:
x

array([6., 7., 5., 3., 1., 8., 9., 0., 2.], dtype=float32)

In [17]:
x[3]

3.0

In [18]:
x[6]

9.0

In [19]:
x = np.array([6, 7, 5, 3, 1, 8.6, 9, 0, 2])

In [20]:
x.dtype

dtype('float64')

In [21]:
x

array([6. , 7. , 5. , 3. , 1. , 8.6, 9. , 0. , 2. ])

In [22]:
x = np.array([6, 7, 5, 3, 1, 8.6, 9, 0, 'hello'])

In [23]:
x

array(['6', '7', '5', '3', '1', '8.6', '9', '0', 'hello'], dtype='<U32')

In [24]:
x.dtype

dtype('<U32')

In [25]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
x = np.arange(1,11,0.5)

In [27]:
x

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [34]:
np.arange(1,11,0.052)

array([ 1.   ,  1.052,  1.104,  1.156,  1.208,  1.26 ,  1.312,  1.364,
        1.416,  1.468,  1.52 ,  1.572,  1.624,  1.676,  1.728,  1.78 ,
        1.832,  1.884,  1.936,  1.988,  2.04 ,  2.092,  2.144,  2.196,
        2.248,  2.3  ,  2.352,  2.404,  2.456,  2.508,  2.56 ,  2.612,
        2.664,  2.716,  2.768,  2.82 ,  2.872,  2.924,  2.976,  3.028,
        3.08 ,  3.132,  3.184,  3.236,  3.288,  3.34 ,  3.392,  3.444,
        3.496,  3.548,  3.6  ,  3.652,  3.704,  3.756,  3.808,  3.86 ,
        3.912,  3.964,  4.016,  4.068,  4.12 ,  4.172,  4.224,  4.276,
        4.328,  4.38 ,  4.432,  4.484,  4.536,  4.588,  4.64 ,  4.692,
        4.744,  4.796,  4.848,  4.9  ,  4.952,  5.004,  5.056,  5.108,
        5.16 ,  5.212,  5.264,  5.316,  5.368,  5.42 ,  5.472,  5.524,
        5.576,  5.628,  5.68 ,  5.732,  5.784,  5.836,  5.888,  5.94 ,
        5.992,  6.044,  6.096,  6.148,  6.2  ,  6.252,  6.304,  6.356,
        6.408,  6.46 ,  6.512,  6.564,  6.616,  6.668,  6.72 ,  6.772,
      

In [29]:
x = np.array([4,6,5,7,8,9])

In [30]:
x * 2

array([ 8, 12, 10, 14, 16, 18])

In [31]:
y = [4,6,5,7,8,9]
y * 2

[4, 6, 5, 7, 8, 9, 4, 6, 5, 7, 8, 9]

In [32]:
x + 10

array([14, 16, 15, 17, 18, 19])

In [35]:
x = np.array([[3,4,5],[7,8,9]])

In [36]:
x

array([[3, 4, 5],
       [7, 8, 9]])

In [37]:
x.size

6

In [38]:
x.shape

(2, 3)

In [39]:
x.reshape(3,2)

array([[3, 4],
       [5, 7],
       [8, 9]])

In [41]:
x = x.flatten()

In [42]:
x

array([3, 4, 5, 7, 8, 9])

In [43]:
x.min()

3

In [44]:
x.mean()

6.0

In [46]:
x.max()

9

In [47]:
x.sort()

In [48]:
x

array([3, 4, 5, 7, 8, 9])